Array Creation Functions

In [ ]:
#importing the numpy

In [26]:
import numpy as np

#creating the numpy array it requires the list
arr1d = np.array([1,2,3,4,5])        # this is the vector (1D)
print(arr1d.ndim)


1


In [27]:
#2d numpy arry having rows and columns (2d matrix)
# 2-rows and 3 columns
arr2d = np.array([[1,2,3],
                  [4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [28]:
#3d array has three axis like a stack of 2d array matrices or we can also call it a "TENSOR"
# in 3d array we have multiple 2d array
arr3d = np.array([
                   [
                    [1,2,3],
                    [4,5,6]
                   ],
                   [
                    [7,8,9],
                    [10,11,12]
                   ]
                ])

print(arr3d.ndim)

3


In [29]:
#we can create the all the type of numpy array integer, float, string, date, boolean, time etc.
#by using the dtype.

#lets create the float type numpy array
float1d_arr = np.array([2.1,3.1,4.1],dtype=float)
print(float1d_arr)

[2.1 3.1 4.1]


In [30]:
# np.arange function in this we define the range of elements in array and array created
myarr = np.arange(1,11)
print(myarr)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
# np.reshape(5,2) function used to convert the 1d array simple array to the 2d array but the condition is that
# the product of values in reshape function equals to the total elements in 1d array

numArr = np.arange(1,21).reshape(10,2)   # 10 x 2 = 20 means ---> 10 rows, 2 columns
print(numArr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [32]:
# np.ones((rows, columns))  ----> used for the initialy insert values in array (all are 1's)
# np.zeros((rows, columns))   ----> used for the initialy insert values in array (all are 0's)
# np.random((rows, columns))  ----> used for the initialy insert values in array (random value)
# all of three functions take tuple as an arguement

print(np.ones((2,2)))

print(np.zeros((2,2)))

print(np.random.random((2,3)))

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[0.71787069 0.11661985 0.55221698]
 [0.382715   0.45486666 0.89921596]]


In [5]:
# np.linspace(x,y,number) it creates a numpy list from X to Y range and (number) is the how many numbers will be in the list
# gives linearly separable points

my_list = np.linspace(-10, 30, 15)
print(my_list)


[-10.          -7.14285714  -4.28571429  -1.42857143   1.42857143
   4.28571429   7.14285714  10.          12.85714286  15.71428571
  18.57142857  21.42857143  24.28571429  27.14285714  30.        ]


In [33]:
# np.identity(3) creates an indenity matrix numpy array.
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Numpy Class Attribute
That can be use with numpy array

In [21]:
a1 = np.arange(1,11)
a2 = np.arange(1,11,dtype=float).reshape(2,5)
a3 = np.arange(16).reshape(2,2,2,2)  #4d array

In [22]:
#ndim (tells the dimension of array)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
4


In [34]:
# shape
# tells the how many number of items in every dimensionand number of rows and columns in numpy array
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a3)

(10,)
(2, 5)
(2, 2, 2, 2)
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [24]:
# size
# tells that how much memory size taken by every item of any array.
print(a3.itemsize)

8


In [37]:
# dtype
# to check the data type of an array element
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64
