Array Creation Functions

In [ ]:
#importing the numpy
#numpy array also called a Vector --> 1d, 2d, 3d, ....

In [2]:
import numpy as np

#creating the numpy array it requires the list
arr1d = np.array([1,2,3,4,5])        # this is the vector (1D)
print(arr1d.ndim)


1


In [27]:
#2d numpy arry having rows and columns (2d matrix)
# 2-rows and 3 columns
arr2d = np.array([[1,2,3],
                  [4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [28]:
#3d array has three axis like a stack of 2d array matrices or we can also call it a "TENSOR"
# in 3d array we have multiple 2d array
arr3d = np.array([
                   [
                    [1,2,3],
                    [4,5,6]
                   ],
                   [
                    [7,8,9],
                    [10,11,12]
                   ]
                ])

print(arr3d.ndim)

3


In [29]:
#we can create the all the type of numpy array integer, float, string, date, boolean, time etc.
#by using the dtype.

#lets create the float type numpy array
float1d_arr = np.array([2.1,3.1,4.1],dtype=float)
print(float1d_arr)

[2.1 3.1 4.1]


In [30]:
# np.arange function in this we define the range of elements in array and array created
myarr = np.arange(1,11)
print(myarr)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
# np.reshape(5,2) function used to convert the 1d array simple array to the 2d array but the condition is that
# the product of values in reshape function equals to the total elements in 1d array

numArr = np.arange(1,21).reshape(10,2)   # 10 x 2 = 20 means ---> 10 rows, 2 columns
print(numArr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [32]:
# np.ones((rows, columns))  ----> used for the initialy insert values in array (all are 1's)
# np.zeros((rows, columns))   ----> used for the initialy insert values in array (all are 0's)
# np.random((rows, columns))  ----> used for the initialy insert values in array (random value)
# all of three functions take tuple as an arguement

print(np.ones((2,2)))

print(np.zeros((2,2)))

print(np.random.random((2,3)))

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[0.71787069 0.11661985 0.55221698]
 [0.382715   0.45486666 0.89921596]]


In [5]:
# np.linspace(x,y,number) it creates a numpy list from X to Y range and (number) is the how many numbers will be in the list
# gives linearly separable points

my_list = np.linspace(-10, 30, 15)
print(my_list)


[-10.          -7.14285714  -4.28571429  -1.42857143   1.42857143
   4.28571429   7.14285714  10.          12.85714286  15.71428571
  18.57142857  21.42857143  24.28571429  27.14285714  30.        ]


In [33]:
# np.identity(3) creates an indenity matrix numpy array.
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Numpy Class Attribute
That can be use with numpy array

In [21]:
a1 = np.arange(1,11)
a2 = np.arange(1,11,dtype=float).reshape(2,5)
a3 = np.arange(16).reshape(2,2,2,2)  #4d array

In [22]:
#ndim (tells the dimension of array)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
4


In [34]:
# shape
# tells the how many number of items in every dimensionand number of rows and columns in numpy array
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a3)

(10,)
(2, 5)
(2, 2, 2, 2)
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [24]:
# size
# tells that how much memory size taken by every item of any array.
print(a3.itemsize)

8


In [37]:
# dtype
# to check the data type of an array element
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


Changing Data Type

In [42]:
#astype(datatype) --> int32, int64, float, bool etc.
# by using this we change the data type of column in file for the memory optimization

a3 = a3.astype(np.int32)
print(a3.dtype)

int32


Array Operations

In [21]:
a1 = np.arange(1,11).reshape(2,5)
a2 = np.arange(20,30).reshape(2,5)
print(a1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
# Scalar and airhtmetic operation on numpy array
# we can perform a +, -, *, /, %, ** to an every element of array. the number we use called a scaler

a1 + 2
a1 - 2
a1 * 2
a1 / 2
a1 ** 2
a1 % 2

#In this 2 is scaler


array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [ ]:
# Relational Operation return True or False after checking condition (on numpy array)
# apply on every item of array
# ==, !=, <, >, <=, >=

a1 > 10
a1 != 2

a1 == 2
a1 >= 2

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
# Vector airthemtic operation
# operation between two or more vector or arrays
first = np.array([1,2,3,4,5,6])
sec = np.array([7,8,9,10,11,12])
print(first + sec)
print(first - sec)
print(first * sec)


[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]


In [42]:
tensor1 = np.arange(1,37).reshape(4,3,3)
print(tensor1)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


Array Operations

In [ ]:
# min / max / sum / product
# axis=0 -> col, axis=1->rows means apply operation on column or a row 
a1 = np.arange(15,30).reshape(3,5)
# print(a1)

print(np.min(a1, axis=1)) 
print(np.max(a1, axis=1))
print(np.sum(a1, axis=0))

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[15 20 25]
[19 24 29]
[60 63 66 69 72]


In [78]:
# mean / median / var / std
# we can also use the axis here 
a2 = np.arange(12,24).reshape(2,6)
# print(a2)

np.mean(a2)
np.median(a2)
np.var(a2, axis=0)
print(np.std(a2, axis=1))

[1.70782513 1.70782513]


In [84]:
# dot product 
# for dot product condition is 
# no. for columns in Matrix A = no. of rows in Matrix B

matrix1 = np.arange(12,24).reshape(3,4)
matrix2 = np.arange(24,36).reshape(4,3)
np.dot(matrix1,matrix2)   

array([[1554, 1608, 1662],
       [2010, 2080, 2150],
       [2466, 2552, 2638]])

In [90]:
#find logs and exponents in numpy
arr = np.arange(1,21).reshape(2,10)
np.log(arr)
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03, 2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08, 4.85165195e+08]])

In [118]:
# round / floor / ceil 
# all are used to convert num --> integer but in differnt way
# give nearset value before point
# give nearest value after point
a1 = np.round(np.random.random((2,2))*100)
a1 = np.floor(np.random.random((2,2))*100)
a1 = np.ceil(np.random.random((2,2))*100)
print(a1)

[[40. 86.]
 [36. 68.]]


Slicing and Indexing (numpy Array)

In [ ]:
a1 = np.arange(10)
a2 = np.arange(1,16).reshape(3,5)
a3 = np.arange(16).reshape(2,4,2)   # 3d / dimension array
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [ ]:
#array[start:stop:stride]   a stride is just the step size when you pick elements from an array.
#like direclty jumps from 0 step to 3 step of stairs
a1[2:8]
a2[1:,2:4]           
a3[1,::3,0:]

array([[ 8,  9],
       [14, 15]])

Slicing in 2d or 3d Vector.

In [ ]:
#2d
a2[:,2]
a2[1,:]

#3d
a3[1,2,:]    # 1 block , 1 row, : all column  (according to index start from 0)
a3[1,:,1]    # 1 block , : all rows, 1 column

array([ 9, 11, 13, 15])

In [191]:
import numpy as np

# Create a 4D tensor with shape (2, 2, 3, 4)
# Meaning: 2 blocks, each with 2 matrices, each matrix 3x4
tensor4d = np.arange(2*2*3*4).reshape(2, 2, 3, 4)

print(tensor4d)
print("Shape:", tensor4d.shape)


[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]
Shape: (2, 2, 3, 4)


In [193]:
tensor4d[1,1,::2,::3]

array([[36, 39],
       [44, 47]])