Array Creation Functions

In [ ]:
#importing the numpy

In [72]:
import numpy as np

#creating the numpy array it requires the list
arr1d = np.array([1,2,3,4,5])        # this is the vector (1D)
print(arr1d.ndim)


1


In [ ]:
#2d numpy arry having rows and columns (2d matrix)
# 2-rows and 3 columns
arr2d = np.array([[1,2,3],
                  [4,5,6]])
print(arr2d)

2


In [ ]:
#3d array has three axis like a stack of 2d array matrices or we can also call it a "TENSOR"
# in 3d array we have multiple 2d array
arr3d = np.array([
                   [
                    [1,2,3],
                    [4,5,6]
                   ],
                   [
                    [7,8,9],
                    [10,11,12]
                   ]
                ])

print(arr3d.ndim)

3


In [ ]:
#we can create the all the type of numpy array integer, float, string, date, boolean, time etc.
#by using the dtype.

#lets create the float type numpy array
float1d_arr = np.array([2.1,3.1,4.1],dtype=float)
print(float1d_arr)

In [ ]:
# np.arange function in this we define the range of elements in array and array created
myarr = np.arange(1,11)
print(myarr)

In [ ]:
# np.reshape(5,2) function used to convert the 1d array simple array to the 2d array but the condition is that
# the product of values in reshape function equals to the total elements in 1d array

numArr = np.arange(1,21).reshape(10,2)   # 10 x 2 = 20 means ---> 10 rows, 2 columns
print(numArr)

In [ ]:
# np.ones((rows, columns))  ----> used for the initialy insert values in array (all are 1's)
# np.zeros((rows, columns))   ----> used for the initialy insert values in array (all are 0's)
# np.random((rows, columns))  ----> used for the initialy insert values in array (random value)
# all of three functions take tuple as an arguement

print(np.ones((2,2)))

print(np.zeros((2,2)))

print(np.random.random((2,3)))

In [ ]:
# np.linspace(x,y,number) it creates a numpy list from X to Y range and (number) is the how many numbers will be in the list
# gives linearly separable points

my_list = np.linspace(-10, 30, 15)
print(my_list)


In [67]:
# np.identity(3) creates an indenity matrix numpy array
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
