In [1]:
# numpy array is better than the python list, specifically design to perform the mathematical operations on numbers without using loops.
# take less memory and compilation time as compared to the python loops.

In [10]:
import numpy as np

In [9]:
# 1D array numpy (1 dimension just a flatten row of numbers)
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d)

[1 2 3 4 5 6]


In [8]:
# 2D array numpy ( 2d dimensial kind of matrix array contains the rows and columns)
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# 3D or n-dimensional array numpy is stack of mutiple 2d array
arr_3d = np.array([[[1,2,3],
                  [4,5,6]],
                  [[7,8,9],
                  [10,11,12]]])

print(f'This is the 3-dim numpy\n', arr_3d)

This is the 3-dim numpy
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
np.ndim(arr_3d)

3

In [20]:
import numpy as np

# A 4D array containing two separate 3D arrays
arr_4d = np.array([
    [ [[1, 2], [3, 4]], [[5, 6], [7, 8]] ],  # First 3D array
    [ [[9, 10], [11, 12]], [[13, 14], [15, 16]] ]  # Second 3D array
])
print(arr_4d)
print(arr_4d.ndim)   # Output: 4
print(arr_4d.shape)  # Output: (2, 2, 2, 2)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
4
(2, 2, 2, 2)


<h1>Numpy Array Creation using built in functions</h1>

In [25]:
# create array with default values 0, means array fills already with 0.
# np.zeros(shape)

zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
# create array with default values 1, means array fills already with 1.

ones_arr = np.ones((3,3))
print(ones_arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
# same np.full((shape), value)    functions helps to create a array with your specific value like 7,8 what every value

nines_arr = np.full((3,4), 9)
print(nines_arr)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [35]:
#create a squence of number in numpy using the 
# np.arange(start, stop, step)
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [38]:
# creating an identity matrix using np.eye()
# np.eye(3)   (3 means 3x3 matrix, and 1 in the diagonal enteries)

identity_matrix= np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<h1>Array Properties</h1>

In [43]:
two_d_arr = np.array([[1, 2, 3],
                      [4, 5, 6]])

print(two_d_arr)
print("Shape:", two_d_arr.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
