In [1]:
import numpy as np
print(np.__version__)

2.2.3


<h1> Array Creation </h1>

<h5>Creating Arrays in numpy</h5>

In [65]:
# np.array([]) 1d, 2d, 3d

In [2]:
# rank-1 numpy array , 1d array
a1 = np.array([1,2,3])
print(a1)
print(type(a1))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# rank-2 numpy array (which has rows and columns), also called 2d-array
a2 = np.array([
  [1,2,3,4],
  [5,6,7,8]
])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# rank-3 numpy array (which has depth, row, column)
# create a rank-3 array, also called multi dimensional array
# create a numpy array with depth 4 , 2 rows, 3 columns
# it is a stack of multiple 2d arrays
a3 = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]],

    [[13, 14, 15],
     [16, 17, 18]],

    [[19, 20, 21],
     [22, 23, 24]]
])

print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]


<h5>Inspect Numpy Array</h5>
<p>shape, len(), ndim(), size(), dtype(), astype(), tolist()</p>

In [5]:
# check the shape of an array using .shape() functions check how many rows and columns
print(a1.shape)
print(a2.shape)  #(2,3) means 2 rows and 1 column
print(a3.shape)  #(3, 2, 3) 3= depth, 2=rows, 3=rows

(3,)
(2, 4)
(4, 2, 3)


In [6]:
# length function , len() func, give total number of elements in the arrays at outer or rank-1 level.
print(len(a1))
print(len(a2))
print(len(a3))

3
2
4


In [7]:
# check the number of dimensions of array. 1d, 2d, 3d.
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [8]:
# dtype is used to check the data type of an array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
int64
int64


In [9]:
# # astype used to change the data type of numpy array.
# astype() does not modify the original array in place.
# It creates a new array with the requested dtype.
# Assigning it back to the same variable (arr = arr.astype(...)) only changes what arr points to; it does not reuse the original array's memory.
# If no other variable references the old array, Python automatically reclaims that memory later.

# change the data type of a2 array
a2_float = np.array(a1, dtype=np.float64)
a2_float.dtype

dtype('float64')

In [10]:
# .tolist() used to convert the numpy array to the python list
print(a1.tolist())
print(a2.tolist())
print(a3.tolist())

[1, 2, 3]
[[1, 2, 3, 4], [5, 6, 7, 8]]
[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]


<h5>Initial Place Holders Function</h5>
<p> np.zero(), np.ones(), np.arange(), np.linspace(), np.logspace(), np.full(), np.seed(), np.random.random(), np.random.randn()
</p>

In [11]:
# fill a numpy array with zeros using np.zeros function, by deine define the rows and columns
num_zero_arr = np.zeros((2,2,3), dtype=np.int16)
num_zero_arr

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int16)

In [12]:
# fill a numpy array with ones using np.ones function, and by the rows and columns
num_ones_arr = np.ones((2,2,3), dtype=np.int16)
num_ones_arr

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [13]:
# np.arange()
# The np.arange() function creates a NumPy array of numbers between a specified start and stop value by defining the step size (or jump) between consecutive elements.
# The stop value is not included in the resulting array.
# syntax : numpy.arange(start, stop, step, dtype=None)

np.arange(10, 25, 2, dtype=np.int16)

array([10, 12, 14, 16, 18, 20, 22, 24], dtype=int16)

In [14]:
# np.linspace()
# In contrast, the np.linspace() function creates a NumPy array of evenly spaced numbers between a specified start and stop value
# by specifying the total number of values required in the array. By default, the stop value = 50 is included in the output.
# syntax: np.linspace(start, stop, num=50, endpoint=True, dtype=None)

np.linspace(75, 100,num=12)

array([ 75.        ,  77.27272727,  79.54545455,  81.81818182,
        84.09090909,  86.36363636,  88.63636364,  90.90909091,
        93.18181818,  95.45454545,  97.72727273, 100.        ])

In [15]:
# =======================================================================
#                         np.logspace()
# ======================================================================
# The np.logspace() function creates a NumPy array of evenly spaced numbers on a "logarithmic scale".
# np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
# Parameters
# start: Starting exponent.
# stop: Ending exponent.
# num (optional): Number of values to generate.
# endpoint (optional): Include the stop exponent (default True).
# base (optional): Base of the logarithm (default is 10).
# dtype (optional): Data type of the output.

In [16]:
np.logspace(0, 2, 3)

array([  1.,  10., 100.])

In [17]:
# np.full() fill an array with your specified values
np.full((2,3), 2)


array([[2, 2, 2],
       [2, 2, 2]])

In [18]:
# create an idenitty matrix in numpy using np.eye() functions

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# Generate a random values in numpy
# The np.random.random() function generates random floating-point numbers that are uniformly distributed between 0.0 (inclusive) and 1.0 (exclusive).
# Inclusive means the boundary value is allowed.

# Exclusive means the boundary value is not allowed.

# For np.random.random():

# 0.0 ≤ x < 1.0
# 0.0 is inclusive → 0.0 is allowed.
# 1.0 is exclusive → 1.0 is not allowed.

np.seed() --> if you want the same sequence of random numbers every time your program runs, you should set the seed before generating random numbers.

In [20]:
my_seed=np.random.seed(42)
random_arr=np.random.random((3,3))
random_arr

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [63]:
# 1. Explanation Note
# np.random.randn(n) generates n random numbers from a normal distribution.
# By default:
# Mean (Center) = 0
# Standard Deviation (Spread) = 1
# Mean tells where the values are centered.
# Standard Deviation tells how spread out the values are from the center.
# + value → Shifts the center (mean).
# * value → Changes the spread (standard deviation).
# Memory Trick: Multiply = Spread, Add = Shift.

#! np.random.randn(n) * standard_deviation + mean

In [67]:
import numpy as np
np.random.seed(10)
# Default: Mean = 0, Standard Deviation = 1
arr = np.random.randn(10)
print(f'Mean = 0, Standard Deviation = 1')
print(arr)

# Change the mean (center)
arr = np.random.randn(10) + 10
# Mean = 10, Standard Deviation = 1
print(f'Mean = 10, Standard Deviation = 1')
print(arr)

# Change the standard deviation (spread)
arr = np.random.randn(10) * 5
# Mean = 0, Standard Deviation = 5
print(f'Mean = 0, Standard Deviation = 5')
print(arr)

# Change both mean and standard deviation
arr = np.random.randn(10) * 5 + 10
# Mean = 10, Standard Deviation = 5
print(f'Mean = 10, Standard Deviation = 5')
print(arr)

Mean = 0, Standard Deviation = 1
[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597 -0.72008556
  0.26551159  0.10854853  0.00429143 -0.17460021]
Mean = 10, Standard Deviation = 1
[10.43302619 11.20303737  9.03493433 11.02827408 10.22863013 10.44513761
  8.86339779 10.13513688 11.484537    8.92019511]
Mean = 0, Standard Deviation = 5
[-9.8886414  -8.71686148  1.33035082 11.92483665  5.61845627  8.36311107
  0.49574608  6.98998189 -1.35623994  3.06602092]
Mean = 10, Standard Deviation = 5
[ 8.66341406  7.25345493 10.66354148  7.61928993 16.5423654  10.9750664
 12.00104994  8.31183831 16.28236132  6.34015249]


Filter out the number from array that less than the 0.5

In [83]:
import numpy as np
np.random.seed(10)
arr = np.abs(np.random.randn(10))

print(f'Original Array')
print(arr)

print(f'Values are very close to 0 if x <= 0.5')
print(arr[arr <= 0.5])

Original Array
[1.3315865  0.71527897 1.54540029 0.00838385 0.62133597 0.72008556
 0.26551159 0.10854853 0.00429143 0.17460021]
Values are very close to 0 if x <= 0.5
[0.00838385 0.26551159 0.10854853 0.00429143 0.17460021]
