In [1]:
# numpy array is better than the python list, specifically design to perform the mathematical operations on numbers without using loops.
# take less memory and compilation time as compared to the python loops.

In [10]:
import numpy as np

In [9]:
# 1D array numpy (1 dimension just a flatten row of numbers)
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d)

[1 2 3 4 5 6]


In [8]:
# 2D array numpy ( 2d dimensial kind of matrix array contains the rows and columns)
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# 3D or n-dimensional array numpy is stack of mutiple 2d array
arr_3d = np.array([[[1,2,3],
                  [4,5,6]],
                  [[7,8,9],
                  [10,11,12]]])

print(f'This is the 3-dim numpy\n', arr_3d)

This is the 3-dim numpy
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
np.ndim(arr_3d)

3

In [20]:
import numpy as np

# A 4D array containing two separate 3D arrays
arr_4d = np.array([
    [ [[1, 2], [3, 4]], [[5, 6], [7, 8]] ],  # First 3D array
    [ [[9, 10], [11, 12]], [[13, 14], [15, 16]] ]  # Second 3D array
])
print(arr_4d)
print(arr_4d.ndim)   # Output: 4
print(arr_4d.shape)  # Output: (2, 2, 2, 2)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
4
(2, 2, 2, 2)


<h1>Numpy Array Creation using built in functions</h1>

In [25]:
# create array with default values 0, means array fills already with 0.
# np.zeros(shape)

zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
# create array with default values 1, means array fills already with 1.

ones_arr = np.ones((3,3))
print(ones_arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
# same np.full((shape), value)    functions helps to create a array with your specific value like 7,8 what every value

nines_arr = np.full((3,4), 9)
print(nines_arr)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [35]:
#create a squence of number in numpy using the 
# np.arange(start, stop, step)
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [38]:
# creating an identity matrix using np.eye()
# np.eye(3)   (3 means 3x3 matrix, and 1 in the diagonal enteries)

identity_matrix= np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<h1>Array Properties</h1>

In [45]:
# find the how many rows and column in the numpy array using the np.shape()

two_d_arr = np.array([[1, 2, 3],
                      [4, 5, 6]])

print(two_d_arr)
print("Shape:", np.shape(two_d_arr))

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [51]:
# check the total number of elements in the array
two_d_arr = np.array([[1, 2, 3], [4, 5, 6]])

print('Total number of elements in the array : ', np.size(two_d_arr))

Total number of elements in the array :  6


In [53]:
#check the dimension of data how it is stored in which dimension? 1d, 2d, 3d
oned_arr = np.array([1,2,3])
twod_arr = np.array([[1,2,3], [4,5,6]])
threed_arr = np.array([[[1,2,3],
                       [4,5,6]],

                       [[10, 11, 12],
                       [13, 14, 15]]])

print(oned_arr.ndim)
print(two_d_arr.ndim)
print(threed_arr.ndim)

1
2
3


In [ ]:
# check the datatype of numpy array using np.dtype()
twod_arr = np.array([[1,2,3.0], [4,5,6]])
print(twod_arr)
print(twod_arr.dtype)


[[1. 2. 3.]
 [4. 5. 6.]]
float64


In [78]:
# change the data type of numpy array from existing one datatype  np.astype()
import numpy as np
age = ['16', '17', '18', '19', '25']  #this is the python list contains the str items/elements

age_arr_numpy = np.array(age)
print(age_arr_numpy.dtype)   # it return the <U2 means data is element is encoded in string we convert it into the int numbers

intAge_arr_numpy = age_arr_numpy.astype(int)
print(intAge_arr_numpy)       # it return the integer ages of array


<U2
[16 17 18 19 25]


<h1>Mathematical Airthmetic Functions Operation in Numpy</h1>

we can use the same airthmetic operations with numpy without using any loop, direct apply

In [93]:
import numpy as np

num_arr = np.array([[1,2,3],
                    [4,5,6]])

print(num_arr + 2)
print(num_arr * 2)
print(num_arr / 2)
print(num_arr ** 2)
print(num_arr % 2)  

[[3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[ 1  4  9]
 [16 25 36]]
[[1 0 1]
 [0 1 0]]


<h1> Aggregation Functions in python </h1>

In [ ]:
# Mean==>The average value of the data
# Variance==>How spread out the data is (in squared units) from mean
# Standard Deviation==>How spread out the data is (in the original units) from means

# Simple analogy
# Imagine students' test scores:
# Mean = the class average.
# Variance = how different the students' scores are from the average.
# Standard deviation = the average amount by which a student's score differs from the class average, expressed in the same units (points) as the scores.

In [105]:
marks_arr = np.array([[48, 49, 50, 50, 51, 52]])

In [104]:
print(marks_arr.sum())
print(marks_arr.mean())
print(marks_arr.min())
print(marks_arr.max())
print(marks_arr.var())
print(marks_arr.std())

300
50.0
48
52
1.6666666666666667
1.2909944487358056


<h1>Indexing in numpy</h1>> 
</br>
<p>In numpy we have both positive and neagtive exist both</p>

In [5]:
import numpy as np
oned_arr = np.array([10,20,30,40,50])
print(oned_arr)

[10 20 30 40 50]


In [9]:
# indexing on 1D array
print(oned_arr[2])
print(oned_arr[-2])

30
40


In [5]:
import numpy as np
twoD_arr = np.array([[1,2,3],
                    [4,5,6]])
print(twoD_arr)
print(twoD_arr[1])  

[[1 2 3]
 [4 5 6]]
[4 5 6]


<h1>Slicing In Numpy and it different techniques</h1>

In [ ]:
# Numpy array slicing syntax
# array[start:stop:step]
# array[start:end] , start to end -1 means the last element is excluded 
# neagtive step, -1 reverse --> Negative indexing in NumPy works exactly like Python lists: it counts from the end of the array.
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[0:5])
print(arr[0::2])
print(arr[2:5:2])

# [10, 20, 30, 40, 50, 60, 70] == [-6 -5 -4 -3 -2 -1]
#negative indexing 
print(arr[-1::-2])

# interview question reverse the numpy without using the loop
arr_interview = np.array([1,3,5,7,9,11,13,15])
arr_interview[-1::-1]


[10 20 30 40 50]
[10 30 50 70]
[30 50]
[70 50 30 10]


np.int64(15)

<h2>Fancy Indexing</h2>

In [32]:
# fancy indexing means selecting the multiple elements at once rather than we select the one.
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[[0, 2, 4]])  # this is copy of an array not edit the original array

[10 30 50]


<h1>Boolean Masking or array Filtering</h1>

In [1]:
# means filtering data base on the conditio True or Fasle, return those values from data that is True
import numpy as np

arr = np.arange(0,100) 
print(arr)

# filter the even numbers from the numpy array
print(arr[arr % 2 == 0])     

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


<h1>Reshaping of Numpy Array</h1>

In [ ]:
import numpy as np

# Reshaping changes the shape (dimensions) of an array without changing its data.
# For example:
# - 1D → 2D
# - 2D → 1D
# - 2D → 3D (if the number of elements remains the same)
#
# reshape() returns a reshaped array. In most cases, it returns a view of the
# original array, so both arrays share the same underlying data.

'''
reshape(new_shape)

Rules:
1. The total number of elements must remain the same.
   Example:
   Original array: 6 elements
   reshape(2, 3) -> 2 × 3 = 6 ✓
   reshape(3, 2) -> 3 × 2 = 6 ✓
   reshape(4, 2) -> 4 × 2 = 8 ✗ (raises ValueError)

2. reshape() does not modify the original array's shape.
   It returns a new array with the requested shape.

3. If the reshaped array is a view (most common case),
   changes made through either array are reflected in the other
   because they share the same underlying memory.
'''

arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:")
print(arr)

reshaped_arr = arr.reshape(2, 3)
print("\nReshaped array:")
print(reshaped_arr)

# Modify the reshaped array
reshaped_arr[0, 0] = 100
print("\nAfter modifying reshaped_arr:")
print(reshaped_arr)

# Original array is also affected
print("\nOriginal array:")
print(arr)

# Modify the original array
arr[2] = 98
print("\nAfter modifying original array:")
print(arr)

# Reshaped array reflects the change
print("\nReshaped array:")
print(reshaped_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[100   2   3]
 [  4   5   6]]
[100   2  98   4   5   6]
[[100   2  98]
 [  4   5   6]]
