In [1]:
# numpy array is better than the python list, specifically design to perform the mathematical operations on numbers without using loops.
# take less memory and compilation time as compared to the python loops.

In [10]:
import numpy as np

In [9]:
# 1D array numpy (1 dimension just a flatten row of numbers)
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d)

[1 2 3 4 5 6]


In [8]:
# 2D array numpy ( 2d dimensial kind of matrix array contains the rows and columns)
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
# 3D or n-dimensional array numpy is stack of mutiple 2d array
import numpy as np
arr_3d = np.array([[[1,2,3],
                  [4,5,6]],
                  [[7,8,9],
                  [10,11,12]]])

print(f'This is the 3-dim numpy\n', arr_3d)

This is the 3-dim numpy
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [41]:
np.ndim(arr_3d)
np.shape(arr_3d)

(2, 2, 3)

In [20]:
import numpy as np

# A 4D array containing two separate 3D arrays
arr_4d = np.array([
    [ [[1, 2], [3, 4]], [[5, 6], [7, 8]] ],  # First 3D array
    [ [[9, 10], [11, 12]], [[13, 14], [15, 16]] ]  # Second 3D array
])
print(arr_4d)
print(arr_4d.ndim)   # Output: 4
print(arr_4d.shape)  # Output: (2, 2, 2, 2)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
4
(2, 2, 2, 2)


<h1>Numpy Array Creation using built in functions</h1>

In [25]:
# create array with default values 0, means array fills already with 0.
# np.zeros(shape)

zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
# create array with default values 1, means array fills already with 1.

ones_arr = np.ones((3,3))
print(ones_arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
# same np.full((shape), value)    functions helps to create a array with your specific value like 7,8 what every value

nines_arr = np.full((3,4), 9)
print(nines_arr)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [35]:
#create a squence of number in numpy using the 
# np.arange(start, stop, step)
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [38]:
# creating an identity matrix using np.eye()
# np.eye(3)   (3 means 3x3 matrix, and 1 in the diagonal enteries)

identity_matrix= np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<h1>Array Properties</h1>

In [45]:
# find the how many rows and column in the numpy array using the np.shape()

two_d_arr = np.array([[1, 2, 3],
                      [4, 5, 6]])

print(two_d_arr)
print("Shape:", np.shape(two_d_arr))

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [51]:
# check the total number of elements in the array
two_d_arr = np.array([[1, 2, 3], [4, 5, 6]])

print('Total number of elements in the array : ', np.size(two_d_arr))

Total number of elements in the array :  6


In [53]:
#check the dimension of data how it is stored in which dimension? 1d, 2d, 3d
oned_arr = np.array([1,2,3])
twod_arr = np.array([[1,2,3], [4,5,6]])
threed_arr = np.array([[[1,2,3],
                       [4,5,6]],

                       [[10, 11, 12],
                       [13, 14, 15]]])

print(oned_arr.ndim)
print(two_d_arr.ndim)
print(threed_arr.ndim)

1
2
3


In [ ]:
# check the datatype of numpy array using np.dtype()
twod_arr = np.array([[1,2,3.0], [4,5,6]])
print(twod_arr)
print(twod_arr.dtype)


[[1. 2. 3.]
 [4. 5. 6.]]
float64


In [78]:
# change the data type of numpy array from existing one datatype  np.astype()
import numpy as np
age = ['16', '17', '18', '19', '25']  #this is the python list contains the str items/elements

age_arr_numpy = np.array(age)
print(age_arr_numpy.dtype)   # it return the <U2 means data is element is encoded in string we convert it into the int numbers

intAge_arr_numpy = age_arr_numpy.astype(int)
print(intAge_arr_numpy)       # it return the integer ages of array


<U2
[16 17 18 19 25]


<h1>Mathematical Airthmetic Functions Operation in Numpy</h1>

we can use the same airthmetic operations with numpy without using any loop, direct apply

In [93]:
import numpy as np

num_arr = np.array([[1,2,3],
                    [4,5,6]])

print(num_arr + 2)
print(num_arr * 2)
print(num_arr / 2)
print(num_arr ** 2)
print(num_arr % 2)  

[[3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[ 1  4  9]
 [16 25 36]]
[[1 0 1]
 [0 1 0]]


<h1> Aggregation Functions in python </h1>

In [ ]:
# Mean==>The average value of the data
# Variance==>How spread out the data is (in squared units) from mean
# Standard Deviation==>How spread out the data is (in the original units) from means

# Simple analogy
# Imagine students' test scores:
# Mean = the class average.
# Variance = how different the students' scores are from the average.
# Standard deviation = the average amount by which a student's score differs from the class average, expressed in the same units (points) as the scores.

In [105]:
marks_arr = np.array([[48, 49, 50, 50, 51, 52]])

In [104]:
print(marks_arr.sum())
print(marks_arr.mean())
print(marks_arr.min())
print(marks_arr.max())
print(marks_arr.var())
print(marks_arr.std())

300
50.0
48
52
1.6666666666666667
1.2909944487358056


<h1>Indexing in numpy</h1>> 
</br>
<p>In numpy we have both positive and neagtive exist both</p>

In [5]:
import numpy as np
oned_arr = np.array([10,20,30,40,50])
print(oned_arr)

[10 20 30 40 50]


In [9]:
# indexing on 1D array
print(oned_arr[2])
print(oned_arr[-2])

30
40


In [5]:
import numpy as np
twoD_arr = np.array([[1,2,3],
                    [4,5,6]])
print(twoD_arr)
print(twoD_arr[1])  

[[1 2 3]
 [4 5 6]]
[4 5 6]


<h1>Slicing In Numpy and it different techniques</h1>

In [ ]:
# Numpy array slicing syntax
# array[start:stop:step]
# array[start:end] , start to end -1 means the last element is excluded 
# neagtive step, -1 reverse --> Negative indexing in NumPy works exactly like Python lists: it counts from the end of the array.
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[0:5])
print(arr[0::2])
print(arr[2:5:2])

# [10, 20, 30, 40, 50, 60, 70] == [-6 -5 -4 -3 -2 -1]
#negative indexing 
print(arr[-1::-2])

# interview question reverse the numpy without using the loop
arr_interview = np.array([1,3,5,7,9,11,13,15])
arr_interview[-1::-1]


[10 20 30 40 50]
[10 30 50 70]
[30 50]
[70 50 30 10]


np.int64(15)

<h2>Fancy Indexing</h2>

In [32]:
# fancy indexing means selecting the multiple elements at once rather than we select the one.
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[[0, 2, 4]])  # this is copy of an array not edit the original array

[10 30 50]


<h1>Boolean Masking or array Filtering</h1>

In [ ]:
# means filtering data base on the condition True or Fasle, return those values from data that is True
import numpy as np

arr = np.arange(0,100) 
print(arr)

# filter the even numbers from the numpy array
print(arr[arr % 2 == 0])     

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


<h1>Reshaping of Numpy Array</h1>

In [11]:
import numpy as np

# Reshaping changes the shape (dimensions) of an array without changing its data.
# For example:
# - 1D → 2D
# - 2D → 1D
# - 2D → 3D (if the number of elements remains the same)
#
# reshape() returns a reshaped array. In most cases, it returns a view of the
# original array, so both arrays share the same underlying data.

'''
reshape(new_shape)

Rules:
1. The total number of elements must remain the same.
   Example:
   Original array: 6 elements
   reshape(2, 3) -> 2 × 3 = 6 ✓
   reshape(3, 2) -> 3 × 2 = 6 ✓
   reshape(4, 2) -> 4 × 2 = 8 ✗ (raises ValueError)

2. reshape() does not modify the original array's shape.
   It returns a new array with the requested shape.

3. If the reshaped array is a view (most common case),
   changes made through either array are reflected in the other
   because they share the same underlying memory.
'''

arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:")
print(arr)

reshaped_arr = arr.reshape(2, 3)
print("\nReshaped array:")
print(reshaped_arr)

# Modify the reshaped array
reshaped_arr[0, 0] = 100
print("\nAfter modifying reshaped_arr:")
print(reshaped_arr)

# Original array is also affected
print("\nOriginal array:")
print(arr)

# Modify the original array
arr[2] = 98
print("\nAfter modifying original array:")
print(arr)

# Reshaped array reflects the change
print("\nReshaped array:")
print(reshaped_arr)

Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]

After modifying reshaped_arr:
[[100   2   3]
 [  4   5   6]]

Original array:
[100   2   3   4   5   6]

After modifying original array:
[100   2  98   4   5   6]

Reshaped array:
[[100   2  98]
 [  4   5   6]]


<h1>Flatten the Array</h1>

In [18]:
'''
means change the array to 1D dimensional form any any N-dimension
Both functions convert any numpy array to 1D array
.ravel() --> view (means change affect both )
.flatten() --> return copy of array (means change dont affect in original array)
'''

arr2D = np.array([[1,2,3], [4,5,6]])
print(arr2D)

print(arr2D.ravel())
print(arr2D.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


<h1> Array Modification</h1>
<p>Insert, Append, Conacatenate the numpy arrays, remove</p>

In [ ]:
'''
np.insert(array, index, value, axis)
array - original array
idnex - 
value -
axis = 0, insert a value row-wise
axis = 1, insert a value column-wise
np.insert() does not modify the existing array. It returns a new array with the inserted values.
'''
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)

# now insert value in the arr
new_arr = np.insert(arr, 2, 25)     # axis = 0 is by default
print(new_arr)

[10 20 30 40 50 60]
[10 20 25 30 40 50 60]


In [22]:
'''
how to insert the element in 2D array?
'''

import numpy as np
arr = np.array([[1,2,3],
               [4,5,6]])

print('Original 2D array')
print(arr)

print('\nAfter Insreting Row')
new_Arr_row = np.insert(arr ,1 ,[5, 7, 9], axis=0)   # row wise insertion, means insert new row.
print(new_Arr_row)

print('\nAfter Insreting Column')
new_Arr_col = np.insert(arr ,1 ,[5, 7], axis=1)   # row wise insertion, means insert new row.
print(new_Arr_col)


Original 2D array
[[1 2 3]
 [4 5 6]]

After Insreting Row
[[1 2 3]
 [5 7 9]
 [4 5 6]]

After Insreting Column
[[1 5 2 3]
 [4 7 5 6]]


In [ ]:
'''
How to append the element in numpy, means add element in the end of array.
numpy.append(arr, values, axis=None)
'''
import numpy as np

# With 1D arr
arr = np.array([12,13,14])
new_arr = np.append(arr, [15, 16, 17])
print(new_arr)

# With 2d arr
arr2D = np.array([[1,2,3],
                [4,5,6]])
new2Darr = np.append(arr2D, [[7],[8]], axis=1)
print(new2Darr)

[12 13 14 15 16 17]
[[1 2 3 7]
 [4 5 6 8]]


In [6]:
'''
how to concatenate the two or more string 
np.concatenate() is a NumPy function used to join multiple arrays along an existing axis.
np.concatenate((array1, array2), axis=0)
axis = 0 --> joins array column wise 
axis = 1 --> means joins array row wise -
'''
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
new_arr_ver = np.concatenate((arr1, arr2), axis=0)
print(new_arr_ver)

[1 2 3 4 5 6]


In [7]:
'''
How to delete the element form numpy array
np.delete(arr, index, axis)
arr - array
index - index can integer/slice/list/array of integers/boolean mask
'''

#1D array
print('1D array Delete')
import numpy as np
arr1d = np.array([10,20,30,40,50])
print(arr1d)
result_1d = np.delete(arr1d, 2)
print(result_1d)

print('\n2D array Delete')
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr2d)

result_2d = np.delete(arr2d, 1, axis=1)
print(result_2d)

1D array Delete
[10 20 30 40 50]
[10 20 40 50]

2D array Delete
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]


<h1>Stacking In Numpy</h1>

In [37]:
'''
In NumPy, stacking means combining multiple arrays into a single array by adding them along a specified axis.
It is commonly used to join arrays either vertically, horizontally, or along a new dimension.

vstack() --> row wise
hstack() --> columns wise
'''
print('With 1D implementation\n')
arr1 = np.array([1,2,3])
arr2 = np.array([7,8,9])
 
print('Vertical stacking means rows wise')
print(np.vstack((arr1, arr2)))

print('\nHorizontal stacking means column wise')
print(np.hstack((arr1, arr2)))

With 1D implementation

Vertical stacking means rows wise
[[1 2 3]
 [7 8 9]]

Horizontal stacking means column wise
[1 2 3 7 8 9]


In [43]:
# With 2D
# Remember this
# vstack → add more rows (go downward ⬇️) vstack() places one array below the other.
# hstack → add more columns (go rightward ➡️) hstack() places one array to the right of the other.

print('With 1D implementation\n')
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.vstack((A, B))
print(result)

result = np.hstack((A, B))
print(result)

With 1D implementation

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


<h1>Splitting in numpy</h1>

In [ ]:
'''
Splitting np.split() divide one array into multiple smaller arrays
np.split(array, indices_or_sections, axis=0)
-array: Input array.
-indices_or_sections:
-An integer → split into equal parts.
-A list of indices → split at/from specific positions.
-axis: Axis along which to split (default is 0, i.e., rows).

np.split() return a list , and in list splits presents
'''

import numpy as np

# With 1D
arr = np.array([10,20,30,40,50,60])
result_arr = np.split(arr, 3)   #array divided into 3 equal parts
result_arr1 = np.split(arr, [2,4])   # [2,4] means first split before 2 index, second split before 4 index
print(result_arr)
print(result_arr1)

print('=================================')

# With 2D
A = np.array([[10,20,30],
               [40,50,60],
               [70,80,90],
               [100,110,120]])

A_split = np.split(A, 2, axis=0)
print(A_split)


B = np.array([[10,20,30],
               [40,50,60],
               [70,80,90],
               [100,110,120]])

B_split = np.split(B, 3, axis=1)
print(B_split)







[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10, 20]), array([30, 40]), array([50, 60])]
[array([[10, 20, 30],
       [40, 50, 60]]), array([[ 70,  80,  90],
       [100, 110, 120]])]
[array([[ 10],
       [ 40],
       [ 70],
       [100]]), array([[ 20],
       [ 50],
       [ 80],
       [110]]), array([[ 30],
       [ 60],
       [ 90],
       [120]])]


In [27]:
numpy_list = []

n1 = np.arange(1,5)
n2 = np.arange(5,10)
n3 = np.arange(10,16)

numpy_list.append(n1)
numpy_list.append(n2)
numpy_list.append(n3)
print(numpy_list)

[array([1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15])]


<h1>Broadcasting Numpy</h1>
<p>The most important concept in numpy</p>

In [40]:
'''
Broadcasting is NumPy's way of automatically expanding the smaller array,
So that it can perform element-wise operations with a larger array.

Broadcasting Rules:
NumPy compares the shapes of two arrays from the last dimension (rightmost) to the first (leftmost).

Two dimensions are compatible if:
1-They are equal, or
2-One of them is 1.

If neither condition is true, broadcasting fails with a ValueError.
'''

"\nBroadcasting is NumPy's way of automatically expanding the smaller array,\nSo that it can perform element-wise operations with a larger array.\n\nBroadcasting Rules:\nNumPy compares the shapes of two arrays from the last dimension (rightmost) to the first (leftmost).\n\nTwo dimensions are compatible if:\n-They are equal, or\n-One of them is 1.\n\nIf neither condition is true, broadcasting fails with a ValueError.\n"

In [47]:
'''Example 1: Same Shape'''
import numpy as np

arr1 = np.array([[10,20],
                [40,50]])
arr2 = np.array([[60,70],
                [80,90]])

'''
shape --> arr1 : (2,2)
shape --> arr2 : (2,2)

Now compare the shapes of arr1 and arr2 from rightmost 
(2,2) == (2,2)  both arrays have same dimensions 2'rows and 2'rows , 1st rule is apply, so broadcasting in possible.
'''

print(arr1 + arr2)

[[ 70  90]
 [120 140]]


In [49]:
'''# Example 2: One Array Dimension is 1'''
A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([10,20,30])

'''
shape --> A : (2,3)
shape --> B : (3)
Numpy treats shape B as the (1,3)

Now compare the shapes of A and B from right most
(2,3)
(1,3)
3==3, 2 vs 1 --> for this rule 2 is applied (here is the one of them is equal to 1)
so 'B' is broadcast to
[[10 20 30]
[10 20 30]]
'''

print(A + B)


[[11 22 33]
 [14 25 36]]


In [52]:
'''Example 3: Column Broadcasting'''
A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([[10],
             [20]])

'''
shape --> A : (2,3)
shape --> B : (2,1)

Now compare the shapes of A and B from right most
(2,3)
(2,1)
2==2, 3 vs 1 --> for this rule 2 is applied (here is the one of them is equal to one)
so 'B' is broadcast to
[[10 10 10]
[20 20 20]]
'''

print(A + B)



[[11 12 13]
 [24 25 26]]


In [ ]:
'''Example 4: Broadcasting Failure'''
A = np.ones((2,3))
B = np.ones((2,2))

'''
shape --> A : (2,3)
shape --> B : (2,2)

Now compare the shapes of A and B from right most left most
(2,3)
(2,2)
3==2, from right most dimension both rules are failed *Neither dimension is equal nor 1.*
so we get the broadcasting error
'''
print(A+B)

<h1>Vectorization</h1>

Vectorization is the process of performing an operation on an entire NumPy array at once instead of processing one element at a time using Python loops.
It is used in metrix operations

In [3]:
# find the sum of elements of numpy array
import numpy as np
arr = np.array(([1,2,3],
               [4,5,6]))

np.sum(arr)

np.int64(21)

In [65]:
arr = np.array([1,2,3])
arr *= 2
print(arr)

[2 4 6]


<h1>Finding the Missing value, and handle Nan values in data using numpy</h1>

In [13]:
#find the Nan in data set using --> np.isnan(array)
import numpy as np
arr = np.array([1,np.nan,2,np.nan,3,4,5])
print(np.isnan(arr))

# In output 
# -False represent data value is not nan
# -True represent data value is nan

#interview can we comapre np.nan with np.nan (Answer in No, we cant compare)
print(np.nan==np.nan) 

[False  True False  True False False False]
False


In [17]:
# replace the Nan data value with the number in data
import numpy as np
arr = np.array([1,np.nan,2,np.nan,3,4,5])
cleaned_array = np.nan_to_num(arr, nan=9)  # by default nan=0
print(cleaned_array)

[1. 9. 2. 9. 3. 4. 5.]


Handling the infinite Values in data set

In [25]:
''' 
first how to identify the infinite values(positve and negative) in the data set
 Syntax:
 -np.isinf(arr)
'''

import numpy as np
arr = np.array([1,2,np.inf, 4, 5, np.inf])
print(np.isinf(arr))

[False False  True False False  True]


In [39]:
'''
How to replace the infinte values with numerical 
Syntax: np.nan_to_num(arr, posinf=1000, neginf=-1000)   
- arr means array contains the infinite value
- posinf means replace positive infinte value with the positive +1000
- neginf means replace neg infinte value with the neg -1000
- these value can change acc. to need not a rule
'''

import numpy as np
arr = np.array([1,2,np.inf, 4, 5, -np.inf])
# arr = np.array([1,2,3, 4, 5, 6])

found = False

if np.any(np.isinf(arr)):
    found = True
    print('Array contains the Infinte value or values')
else:
    print('Clear, No infinite value')

if found is True:
    clean_arr = np.nan_to_num(arr, posinf=100, neginf=-100)
    print(clean_arr)

Array contains the Infinte value or values
[   1.    2.  100.    4.    5. -100.]
